### ISSUE TITLE
`terraform fmt` should be run as a lint step

### ISSUE THREAD

**Issue by jufemaiz** [COzero/arrakis-buildkite-plugin#12]
Just as the title says.

We should lint the code and fail anything that changes due to a terraform fmt.

**Comment by mubeta06** [comment]
Looks like fmt supports this https://www.terraform.io/docs/commands/fmt.html through the "check" flag. The plugin is probably not the place to be implementing this but rather in the Buildkite Pipeline remote module over in bitbucket.

**Comment by jufemaiz** [comment]
👍 

Went here as it was the reference in the pipeline.yml. Probably indicative that it needs a little more docs there too. Will look at.

**Comment by jufemaiz** [comment]
:
